services:
  postgres-17:
    container_name: postgres-17
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - pginit17:/docker-entrypoint-initdb.d
      - pgdata17:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-guacadb}
      POSTGRES_PASSWORD:
      POSTGRES_INITDB_ARGS: --auth-host=md5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  guacd:
    container_name: guacd
    image: guacamole/guacd:1.5.5
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  guacamole:
    container_name: guacamole
    image: guacamole/guacamole:1.5.5
    restart: unless-stopped
    ports:
      - 8084:8080/tcp # guacamole is on :8080/guacamole, not /.
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres-17
      POSTGRES_DATABASE: ${POSTGRES_USER:-guacadb}
      POSTGRES_USER: ${POSTGRES_USER:-guacadb}
      POSTGRES_PASSWORD:
    depends_on:
      - postgres-17
      - guacd
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  pginit17:
  pgdata17:
