services:
  postgres-17:
    container_name: ${COMPOSE_PROJECT_NAME}_postgres-17
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - pginit17:/docker-entrypoint-initdb.d
      - pgdata17:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-guacadb}
      POSTGRES_PASSWORD:
      POSTGRES_INITDB_ARGS: --auth-host=md5
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  guacd:
    container_name: ${COMPOSE_PROJECT_NAME}_guacd
    image: guacamole/guacd:1.6.0
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  guacamole:
    container_name: ${COMPOSE_PROJECT_NAME}_guacamole
    image: guacamole/guacamole:1.6.0
    restart: unless-stopped
    ports:
      - 8084:8080/tcp # guacamole is on :8080/guacamole, not /.
    environment:
      GUACD_HOSTNAME: guacd
      #POSTGRES_HOSTNAME: postgres-17
      #POSTGRES_DATABASE: ${POSTGRES_USER:-guacadb}
      #POSTGRES_USER: ${POSTGRES_USER:-guacadb}
      #POSTGRES_PASSWORD:
      POSTGRESQL_ENABLED: "true"
      POSTGRESQL_HOSTNAME: postgres-17
      POSTGRESQL_DATABASE: ${POSTGRESQL_USER:-guacadb}
      POSTGRESQL_USER: ${POSTGRESQL_USER:-guacadb}
      POSTGRESQL_PASSWORD:      
    depends_on:
      - postgres-17
      - guacd
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  pginit17:
  pgdata17:
