name: validate-yaml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Validate YAML file
        run: yamllint -c .github/.yamllint .
